title: Hacker:Bio
subtitle: Weekly Live Podcast that interviews technologists from around the world about their craft
description: An exploration into the daily lives of Software Developers, Hardware Tinkers, Engineers and Technologists to better understand the culture, mindset and motivation of this generation.

url: https://hacker.bio

collections_dir: _collections

timezone: America/New_York

future: true

exclude:
  - ssl
  - Dockerfile
  - docker-compose.yml

collections:
  hackers:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      type: hackers
    values:
      layout: hacker

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
